"""init

Revision ID: 0867c02a8d82
Revises: 
Create Date: 2021-11-05 13:36:52.341330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0867c02a8d82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_date'), 'activities', ['date'], unique=False)
    op.create_index(op.f('ix_activities_deadline'), 'activities', ['deadline'], unique=False)
    op.create_index(op.f('ix_activities_description'), 'activities', ['description'], unique=False)
    op.create_index(op.f('ix_activities_status'), 'activities', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_status'), table_name='activities')
    op.drop_index(op.f('ix_activities_description'), table_name='activities')
    op.drop_index(op.f('ix_activities_deadline'), table_name='activities')
    op.drop_index(op.f('ix_activities_date'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
